## Importação das bibliotecas e carregamento dos dados

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive, files
import os

# Gráficos -- Seaborn e matplotlib
import seaborn as sns
import matplotlib.pyplot as plt

pd.options.display.float_format = '{:.2f}'.format

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)
os.chdir('/content/drive/My Drive/dados/SUSEP/RAW')

Mounted at /content/drive

In [3]:
df = pd.read_csv('arq_casco_comp.csv', sep=';', decimal=',')

/tmp/ipython-input-368772002.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('arq_casco_comp.csv', sep=';', decimal=',')

## Análise Exploratória

In [4]:
# Amostragem das 5 primeiras linhas
df.head()

,COD_TARIF,REGIAO,COD_MODELO,ANO_MODELO,SEXO,IDADE,EXPOSICAO1,PREMIO1,EXPOSICAO2,PREMIO2,...,INDENIZ1,FREQ_SIN2,INDENIZ2,FREQ_SIN3,INDENIZ3,FREQ_SIN4,INDENIZ4,FREQ_SIN9,INDENIZ9,ENVIO
0,1,12,025185-2,2016,M,3,6.75,8112.76,0,0,...,0,0,0,0,0,0,0,3,345,2019B
1,1,12,025214-0,2015,J,3,1.08,1232.99,0,0,...,0,0,0,0,0,0,0,0,0,2019B
2,3,12,001388-9,2014,M,4,0.50,884.72,0,0,...,0,0,0,0,0,0,0,0,0,2019B
3,3,07,001453-2,2019,J,5,5.03,15386.13,0,0,...,0,0,0,0,0,0,0,0,0,2019B
4,7,21,033080-9,2012,0,0,0.50,1291.73,0,0,...,0,0,0,0,0,0,0,0,0,2019B

In [5]:
# Quantidade de linhas (observações) e colunas (variáveis)
df.shape

(3128606, 22)

Há informações sobre 3.128.606 observações (linhas) e são 22 variáveis.

In [6]:
# Nomes das variáveis
df.columns

Index(['COD_TARIF', 'REGIAO', 'COD_MODELO', 'ANO_MODELO', 'SEXO', 'IDADE',
       'EXPOSICAO1', 'PREMIO1', 'EXPOSICAO2', 'PREMIO2', 'IS_MEDIA',
       'FREQ_SIN1', 'INDENIZ1', 'FREQ_SIN2', 'INDENIZ2', 'FREQ_SIN3',
       'INDENIZ3', 'FREQ_SIN4', 'INDENIZ4', 'FREQ_SIN9', 'INDENIZ9', 'ENVIO'],
      dtype='object')

In [7]:
# informações sobre os tipos de dados
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3128606 entries, 0 to 3128605
Data columns (total 22 columns):
 #   Column      Dtype
---  ------      -----
 0   COD_TARIF   int64
 1   REGIAO      object
 2   COD_MODELO  object
 3   ANO_MODELO  object
 4   SEXO        object
 5   IDADE       int64
 6   EXPOSICAO1  float64
 7   PREMIO1     float64
 8   EXPOSICAO2  int64
 9   PREMIO2     int64
 10  IS_MEDIA    float64
 11  FREQ_SIN1   int64
 12  INDENIZ1    int64
 13  FREQ_SIN2   int64
 14  INDENIZ2    int64
 15  FREQ_SIN3   int64
 16  INDENIZ3    int64
 17  FREQ_SIN4   int64
 18  INDENIZ4    int64
 19  FREQ_SIN9   int64
 20  INDENIZ9    int64
 21  ENVIO       object
dtypes: float64(3), int64(14), object(5)
memory usage: 525.1+ MB

In [8]:
# Função do pandas para visualizar até 50 colunas ou o número desejado, 24 colunas.
pd.set_option('display.max_columns', 24)

In [9]:
# mostrar as 5 últimas linhas já com todas as 22 colunas sendo exibidas
df.tail()

,COD_TARIF,REGIAO,COD_MODELO,ANO_MODELO,SEXO,IDADE,EXPOSICAO1,PREMIO1,EXPOSICAO2,PREMIO2,IS_MEDIA,FREQ_SIN1,INDENIZ1,FREQ_SIN2,INDENIZ2,FREQ_SIN3,INDENIZ3,FREQ_SIN4,INDENIZ4,FREQ_SIN9,INDENIZ9,ENVIO
3128601,1,39,023064-2,2016,M,5,0.09,110.91,0,0,57469.00,0,0,0,0,0,0,0,0,0,0,2019B
3128602,1,04,023112-6,2014,F,5,1.49,1358.05,0,0,34493.45,0,0,0,0,0,0,0,0,0,0,2019B
3128603,3,39,021338-1,2016,F,3,0.50,2944.86,0,0,134606.04,0,0,0,0,0,0,0,0,0,0,2019B
3128604,1,18,024145-8,2010,J,0,1.13,1547.92,0,0,19016.92,0,0,0,0,0,0,0,0,0,0,2019B
3128605,1,23,005404-6,2016,F,3,5.40,6549.89,0,0,45567.84,0,0,1,1065,0,0,0,0,0,0,2019B

In [10]:
# Amostragem de 10 linhas aleatóRias de cada coluna
df.sample(10)

,COD_TARIF,REGIAO,COD_MODELO,ANO_MODELO,SEXO,IDADE,EXPOSICAO1,PREMIO1,EXPOSICAO2,PREMIO2,IS_MEDIA,FREQ_SIN1,INDENIZ1,FREQ_SIN2,INDENIZ2,FREQ_SIN3,INDENIZ3,FREQ_SIN4,INDENIZ4,FREQ_SIN9,INDENIZ9,ENVIO
1714290,3,01,015085-1,2013,M,3,4.29,8522.25,0,0,57669.04,0,0,0,0,0,0,0,0,3,772,2019B
2594792,3,11,003086-4,1996,F,3,0.50,482.01,0,0,16035.00,0,0,0,0,0,0,0,0,0,0,2019B
2536865,1,09,014081-3,2017,F,3,22.57,31904.65,0,0,59367.75,0,0,2,11080,0,0,0,0,7,2994,2019B
616907,3,02,003321-9,2010,J,0,0.50,389.12,0,0,41218.00,0,0,0,0,0,0,0,0,0,0,2019B
2394547,1,25,001273-4,2014,M,4,2.51,1963.10,0,0,29838.95,0,0,0,0,0,0,0,0,0,0,2019B
2094948,1,16,001354-4,2015,M,3,10.42,12320.72,0,0,41639.74,0,0,1,5129,0,0,0,0,1,542,2019B
15265,1,20,004471-7,2017,J,0,1.81,2256.33,0,0,56493.18,0,0,0,0,0,0,0,0,0,0,2019B
463010,5,39,827079-1,2014,F,1,0.50,164.87,0,0,4326.31,0,0,0,0,0,0,0,0,0,0,2019B
1550365,4,14,504077-9,2008,M,2,0.50,1164.32,0,0,61337.14,0,0,0,0,0,0,0,0,0,0,2019B
711543,1,11,005477-1,2017,F,4,6.56,9672.06,0,0,59723.00,0,0,0,0,0,0,0,0,0,0,2019B

Resumo estatístico dos dados.

Visão geral da média, mínimo, máximo e quartis (25%, 50% e 75%).

Insights iniciais:

- Primeiro quartil (25%) -
- Mediana (50%) -
- Terceiro quartil (75%) -
- Máximo -

In [11]:
df.describe()

,COD_TARIF,IDADE,EXPOSICAO1,PREMIO1,EXPOSICAO2,PREMIO2,IS_MEDIA,FREQ_SIN1,INDENIZ1,FREQ_SIN2,INDENIZ2,FREQ_SIN3,INDENIZ3,FREQ_SIN4,INDENIZ4,FREQ_SIN9,INDENIZ9
count,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00,3128606.00
mean,2.16,2.87,2.62,3885.52,0.00,0.00,53275.40,0.02,652.55,0.15,823.38,0.02,798.71,0.00,25.83,0.64,448.84
std,1.65,1.69,10.29,15158.43,0.00,0.00,53901.20,0.23,10199.74,2.63,11771.96,0.15,8478.66,0.03,1572.59,3.75,4871.72
min,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,1.00,2.00,0.45,440.47,0.00,0.00,23153.98,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,1.00,3.00,0.55,1080.05,0.00,0.00,39602.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
75%,3.00,4.00,1.77,2932.10,0.00,0.00,66281.46,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
max,9.00,5.00,2727.37,5739441.22,0.00,0.00,3929298.21,154.00,7819350.00,1989.00,18555890.00,73.00,3909156.00,4.00,649961.00,445.00,2421501.00

## Ajustes nos dados

Antes de começar a alterar algumas coisas no conjunto de dados, vamos realizar uma cópia deles com o nome 'casco':

In [12]:
# Cópia de trabalho para não mexer no df original
casco = df.copy()

# Renomear colunas para snake_case (mantendo sentido do dicionário)
casco = casco.rename(columns={
    "COD_TARIF": "categoria",
    "REGIAO": "regiao",
    "COD_MODELO": "modelo",
    "ANO_MODELO": "ano",
    "SEXO": "sexo",
    "IDADE": "faixa_etaria",
    "EXPOSICAO1": "exposicao1",
    "PREMIO1": "premio1",
    "EXPOSICAO2": "exposicao2",   # não utilizado (segundo o dicionário)
    "PREMIO2": "premio2",         # não utilizado
    "IS_MEDIA": "is_media",
    "FREQ_SIN1": "freq_sin1",
    "INDENIZ1": "indeniz1",
    "FREQ_SIN2": "freq_sin2",
    "INDENIZ2": "indeniz2",
    "FREQ_SIN3": "freq_sin3",
    "INDENIZ3": "indeniz3",
    "FREQ_SIN4": "freq_sin4",
    "INDENIZ4": "indeniz4",
    "FREQ_SIN9": "freq_sin9",
    "INDENIZ9": "indeniz9",
    "ENVIO": "envio"
})

casco.head(3)

,categoria,regiao,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio
0,1,12,025185-2,2016,M,3,6.75,8112.76,0,0,59889.52,0,0,0,0,0,0,0,0,3,345,2019B
1,1,12,025214-0,2015,J,3,1.08,1232.99,0,0,32457.32,0,0,0,0,0,0,0,0,0,0,2019B
2,3,12,001388-9,2014,M,4,0.50,884.72,0,0,46034.00,0,0,0,0,0,0,0,0,0,0,2019B

Verificar se há dados faltantes:

In [13]:
# Verificação de dados faltantes
# sem sum() temos apenas True e False
casco.isna().sum()

categoria       0
regiao          0
modelo          0
ano             0
sexo            0
faixa_etaria    0
exposicao1      0
premio1         0
exposicao2      0
premio2         0
is_media        0
freq_sin1       0
indeniz1        0
freq_sin2       0
indeniz2        0
freq_sin3       0
indeniz3        0
freq_sin4       0
indeniz4        0
freq_sin9       0
indeniz9        0
envio           0
dtype: int64

In [17]:
# Normalização do sexo
map_sexo = {"M":"M","F":"F","J":"Jurídica","0":"Não definido", " ":"Não definido"}
casco["sexo"] = casco["sexo"].map(map_sexo).fillna(casco["sexo"])

# Sinalizar possíveis valores negativos em prêmios/indenizações/exposição
neg_flags = {
    "exposicao1_neg": (casco["exposicao1"] < 0).sum(),
    "premio1_neg": (casco["premio1"] < 0).sum(),
    "indeniz_total_neg": (casco[["indeniz1","indeniz2","indeniz3","indeniz4","indeniz9"]].sum(axis=1) < 0).sum()
}
neg_flags

{'exposicao1_neg': np.int64(0),
 'premio1_neg': np.int64(0),
 'indeniz_total_neg': np.int64(0)}

In [18]:
casco['sexo'].unique()

array(['M', 'Jurídica', 'Não definido', 'F'], dtype=object)

In [19]:
casco.sample(10)

,categoria,regiao,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio
2900162,9,15,999999-9,1998,Jurídica,3,0.50,1.98,0,0,0.00,0,0,0,0,0,0,0,0,0,0,2019B
3009426,2,11,035039-7,2010,M,5,0.92,4692.75,0,0,177820.87,0,0,0,0,0,0,0,0,0,0,2019B
892126,1,15,001325-0,2013,M,5,2.97,2925.38,0,0,32412.07,0,0,0,0,0,0,0,0,0,0,2019B
635784,1,27,014082-1,2017,F,2,0.05,83.40,0,0,56067.00,0,0,0,0,0,0,0,0,0,0,2019B
1754499,3,13,002075-3,2004,M,5,1.73,1871.64,0,0,29604.24,0,0,0,0,0,0,0,0,1,36,2019B
222261,1,19,002111-3,2017,F,3,31.26,68687.12,0,0,86998.72,0,0,0,0,0,0,0,0,3,910,2019B
834940,3,16,025230-1,2017,M,3,4.43,8245.79,0,0,59626.52,0,0,1,56896,0,0,0,0,4,1070,2019B
902027,1,21,004339-7,2009,M,2,1.42,1957.65,0,0,19838.73,0,0,0,0,0,0,0,0,0,0,2019B
91150,4,17,515072-8,2004,Não definido,0,0.00,0.00,0,0,0.00,0,0,0,0,0,0,0,0,4,2022,2019B
327980,2,21,015104-1,2012,F,3,0.50,717.08,0,0,50965.00,0,0,0,0,0,0,0,0,0,0,2019B

In [ ]:
# Criei um df backup (casco_backup) para usar quando necessário
# casco_backup = casco.copy()

## Uso de dicionários para substituir códigos por categorias

* Para que possamos substituir os códigos de algumas variáveis pelas suas ocorrências, vamos criar dicionários.

* O dicionário é um tipo de dado em que temos o par 'chave: valor', sendo que a chave tem que ser única para aquele dicionário.

* Para realizar as substituições que vou mostrar, é preciso baixar os dados referentes ao segundo semestre de 2020 e lá estarão algumas planilhas importantes.

In [20]:
casco.head()

,categoria,regiao,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio
0,1,12,025185-2,2016,M,3,6.75,8112.76,0,0,59889.52,0,0,0,0,0,0,0,0,3,345,2019B
1,1,12,025214-0,2015,Jurídica,3,1.08,1232.99,0,0,32457.32,0,0,0,0,0,0,0,0,0,0,2019B
2,3,12,001388-9,2014,M,4,0.50,884.72,0,0,46034.00,0,0,0,0,0,0,0,0,0,0,2019B
3,3,07,001453-2,2019,Jurídica,5,5.03,15386.13,0,0,130695.64,0,0,0,0,0,0,0,0,0,0,2019B
4,7,21,033080-9,2012,Não definido,0,0.50,1291.73,0,0,134337.99,0,0,0,0,0,0,0,0,0,0,2019B

### CATEGORIA

Para a variável 'CATEGORIA':

Os códigos estão na tabela auxiliar 'auto_cat' que possui definição no Manual da Autoseg;

Definição: auto_cat – código de descrição de categorias tarifárias;

Como são poucos códigos, vamos criar o dicionário de forma manual;

Realizar a substituição.

Manual da Autoseg:

Categoria:
* 1: Carro nacional - Passeio nacional
* 2: Carro importado - Passeio importado
* 3: Pick-up (nacional e importado)
* 4: Veículo de Carga (nacional e importado)
* 5: Motocicleta (nacional e importado)
* 6: Ônibus (nacional e importado)
* 7: Utilitários (nacional e importado)
* 9: Outros

In [21]:
# Observação dos valores únicos da coluna categoria
casco['categoria'].unique()

array([1, 3, 7, 2, 9, 5, 4, 6])

In [22]:
# criação do dicionário de categorias
cat_d = {
    1: 'Carro_nacional',
    2: 'Carro_importado',
    3: 'Pick-up',
    4: 'Veículo_carga',
    5: 'Motocicleta',
    6: 'Ônibus',
    7: 'Utilitários',
    9: 'Outros'
}

# Criamos uma nova coluna com a descrição da categoria (categoria_desc)
# e colocamos a descrição do dicionário usando a função map
casco['categoria_desc'] = casco['categoria'].map(cat_d).astype('string')

# (opcional) transformar em categórico para análises/plots mais leves
casco['categoria_desc'] = casco['categoria_desc'].astype('category')

# checar
casco[['categoria','categoria_desc']].head()

   categoria  categoria_desc
0          1  Carro_nacional
1          1  Carro_nacional
2          3         Pick-up
3          3         Pick-up
4          7     Utilitários

In [23]:
casco.head(5)

,categoria,regiao,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio,categoria_desc
0,1,12,025185-2,2016,M,3,6.75,8112.76,0,0,59889.52,0,0,0,0,0,0,0,0,3,345,2019B,Carro_nacional
1,1,12,025214-0,2015,Jurídica,3,1.08,1232.99,0,0,32457.32,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional
2,3,12,001388-9,2014,M,4,0.50,884.72,0,0,46034.00,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up
3,3,07,001453-2,2019,Jurídica,5,5.03,15386.13,0,0,130695.64,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up
4,7,21,033080-9,2012,Não definido,0,0.50,1291.73,0,0,134337.99,0,0,0,0,0,0,0,0,0,0,2019B,Utilitários

### REGIÃO

Para a variável 'REGIÃO':

Os códigos estão na tabela auxiliar 'auto_reg' que possui definição no Manual da Autoseg;

Definição: auto_reg – código e descrição de regiões de circulação;

Como são poucos códigos, vamos criar o dicionário de forma manual;

Realizar a substituição.

In [32]:
# eu especifiquei as subpastas onde os arquivos se encontram
# dentro do meu google drive: /dados/Autoseg2021A/
reg = pd.read_csv('/content/drive/My Drive/dados/SUSEP/RAW/auto_reg.csv', sep=';', encoding='latin1')

In [33]:
# criar o dicionário usando a coluna 'CODIGO' como chave
# e a coluna 'DESCRICAO' para fazer a substituição
reg_d = reg.set_index('CODIGO')['DESCRICAO'].to_dict()

In [34]:
reg_d

{0.0: 'Não informado',
 1.0: 'RS - Met. Porto Alegre e Caxias do Sul',
 2.0: 'RS - Demais regiões',
 3.0: 'SC - Met. Florianópolis e Sul',
 4.0: 'SC - Oeste',
 5.0: 'SC - Blumenau e demais regiões',
 6.0: 'PR - F.Iguaþu-Medianeira-Cascavel-Toledo',
 7.0: 'PR - Met. Curitiba',
 8.0: 'PR - Demais regiões',
 9.0: 'SP - Vale do Paraíba e Ribeira',
 10.0: 'SP - Litoral Norte e Baixada Santista',
 11.0: 'SP - Met. de São Paulo',
 12.0: 'SP - Grande Campinas',
 13.0: 'SP - Ribeirão Preto e Demais Mun. de Campinas',
 14.0: 'MG - Triângulo mineiro',
 15.0: 'MG - Sul',
 16.0: 'MG - Met.BH-Centro Oeste-Zona Mata-C. Vertentes',
 17.0: 'MG - Vale do Aço-Norte-Vale Jequitinhonha',
 18.0: 'RJ - Met. do Rio de Janeiro',
 19.0: 'RJ - Interior',
 20.0: 'ES - Espírito Santo',
 21.0: 'BA - Bahia',
 22.0: 'SE - Sergipe',
 23.0: 'PE - Pernambuco',
 24.0: 'PB - Paraíba',
 25.0: 'RN - Rio Grande do Norte',
 26.0: 'AL - Alagoas',
 27.0: 'CE - Ceará',
 28.0: 'PI - Piaui',
 29.0: 'MA - Maranhão',
 30.0: 'PA - Pará',
 31.0: 'AM - Amazonas',
 32.0: 'AP - Amapá',
 33.0: 'RO - Rondônia',
 34.0: 'RR - Roraima',
 35.0: 'AC - Acre',
 36.0: 'MT - Mato Grosso',
 37.0: 'MS - Mato Grosso do Sul',
 38.0: 'DF - Brasília',
 39.0: 'GO - Goiás',
 40.0: 'TO - Tocantins',
 41.0: 'GO - Sudeste de Goiás',
 99.0: 'Não informado',
 nan: 'Não informado'}

In [36]:
casco.head()

,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio,categoria_desc,regiao_cod,regiao_desc
0,025185-2,2016,M,3,6.75,8112.76,0,0,59889.52,0,0,0,0,0,0,0,0,3,345,2019B,Carro_nacional,12,SP - Grande Campinas
1,025214-0,2015,Jurídica,3,1.08,1232.99,0,0,32457.32,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,12,SP - Grande Campinas
2,001388-9,2014,M,4,0.50,884.72,0,0,46034.00,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,12,SP - Grande Campinas
3,001453-2,2019,Jurídica,5,5.03,15386.13,0,0,130695.64,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,7,PR - Met. Curitiba
4,033080-9,2012,Não definido,0,0.50,1291.73,0,0,134337.99,0,0,0,0,0,0,0,0,0,0,2019B,Utilitários,21,BA - Bahia

In [35]:
# 1) Garanta que a coluna 'regiao' está como inteiro "nullable" (Int64) para casar com as chaves do dict
casco["regiao_cod"] = pd.to_numeric(casco["regiao"], errors="coerce").astype("Int64")

# 2) Faça o map usando o dicionário (chaves inteiras -> descrição)
casco["regiao_desc"] = casco["regiao_cod"].map(reg_d)

# 3) (opcional) Transforme em categórico para melhorar performance em análises
# casco["regiao_desc"] = casco["regiao_desc"].astype("category")

# 4) Verifique
casco[["regiao_cod","regiao_desc"]].head()
casco["regiao_desc"].value_counts(dropna=False).head(10)

KeyError: 'regiao'

In [28]:
casco["regiao_cod"].unique()

<IntegerArray>
[  12,    7,   21,   26,   10,    8,    2,   17,    1,   20,    9,   11,   30,
   18,   22,   29,   28,   39,   13,   25,   23,    5,   24,   15,   38,   16,
   37,   14,   40,   19,    4,   34,   27,    3,   99,   36, <NA>,    6,   32,
   31,   41,    0,   35,   33]
Length: 44, dtype: Int64

In [29]:
casco.head(5)

,categoria,regiao,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,...,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio,categoria_desc,regiao_cod,regiao_desc
0,1,12,025185-2,2016,M,3,6.75,8112.76,0,0,59889.52,0,...,0,0,0,0,0,0,3,345,2019B,Carro_nacional,12,SP - Grande Campinas
1,1,12,025214-0,2015,Jurídica,3,1.08,1232.99,0,0,32457.32,0,...,0,0,0,0,0,0,0,0,2019B,Carro_nacional,12,SP - Grande Campinas
2,3,12,001388-9,2014,M,4,0.50,884.72,0,0,46034.00,0,...,0,0,0,0,0,0,0,0,2019B,Pick-up,12,SP - Grande Campinas
3,3,07,001453-2,2019,Jurídica,5,5.03,15386.13,0,0,130695.64,0,...,0,0,0,0,0,0,0,0,2019B,Pick-up,7,PR - Met. Curitiba
4,7,21,033080-9,2012,Não definido,0,0.50,1291.73,0,0,134337.99,0,...,0,0,0,0,0,0,0,0,2019B,Utilitários,21,BA - Bahia

In [30]:
# Dropando as colunas 'categoria' e 'regiao' do nosso DF.
casco.drop(['categoria', 'regiao'], axis=1, inplace=True)

In [31]:
casco.head(5)

,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio,categoria_desc,regiao_cod,regiao_desc
0,025185-2,2016,M,3,6.75,8112.76,0,0,59889.52,0,0,0,0,0,0,0,0,3,345,2019B,Carro_nacional,12,SP - Grande Campinas
1,025214-0,2015,Jurídica,3,1.08,1232.99,0,0,32457.32,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,12,SP - Grande Campinas
2,001388-9,2014,M,4,0.50,884.72,0,0,46034.00,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,12,SP - Grande Campinas
3,001453-2,2019,Jurídica,5,5.03,15386.13,0,0,130695.64,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,7,PR - Met. Curitiba
4,033080-9,2012,Não definido,0,0.50,1291.73,0,0,134337.99,0,0,0,0,0,0,0,0,0,0,2019B,Utilitários,21,BA - Bahia

### MODELO

Para a variável 'MODELO':

* Há uma planilha pronta com os códigos e as descrições ('auto2_vei.csv'), vamos carregá-la;
* Criar o dicionário de substituição a partir da planilha;
* Realizar a substituição usando map() e não replace() para agilizar;
* Alterar o nome da variável para 'MODELO'.

In [37]:
# checar quantas ocorrências de cada COD_MODELO existem
casco['modelo'].value_counts()

modelo
999999-9    19513
004370-2     7127
002111-3     6723
003281-6     6283
014045-7     6210
            ...
022059-0        1
808001-1        1
515172-4        1
513294-0        1
021084-6        1
Name: count, Length: 8016, dtype: int64

In [38]:
# carregar a planilha com as codificações dos modelos de automóveis
vei = pd.read_csv('/content/drive/My Drive/dados/SUSEP/RAW/auto2_vei.csv', sep=';', encoding='latin1')

In [39]:
vei.head()

     CODIGO               DESCRICAO               GRUPO  COD_GRUPO
0  038003-2  Acura - Integra GS 1.8               ACURA          1
1  038002-4  Acura - Legend 3.2/3.5               ACURA          1
2  038001-6         Acura - NSX 3.0               ACURA          1
3  840015-6          ADLY - ATV 100  ADLY MOTOS - TODAS          2
4  840014-8           ADLY - ATV 50  ADLY MOTOS - TODAS          2

In [40]:
# criar o dicionário usando a coluna 'CODIGO' como chave
# e a coluna 'GRUPO' para fazer a substituição
# poderia ser a coluna 'GRUPO'
vei_d = vei.set_index('CODIGO')['GRUPO'].to_dict()

In [41]:
# substituir os códigos pelas descrições usando map()
# já criando a nova variável
casco['modelo']= casco['modelo'].map(vei_d)

In [42]:
# checar quantas ocorrências de cada valor existem após a alteração
casco['modelo'].value_counts().head(10)

modelo
FIAT STRADA              66355
HYUNDAI HB20             61578
TOYOTA HILUX             54742
GM CHEVROLET S-10        53808
HONDA MOTOS ATE 450CC    53316
VW VOLKSWAGEN GOL 1.0    51632
FORD ECO SPORT           49857
RENAULT SANDERO          48049
TOYOTA COROLLA           46213
VW VOLKSWAGEN SAVEIRO    44506
Name: count, dtype: int64

In [44]:
casco['modelo'].isna().sum()

np.int64(7726)

In [45]:
# Contar strings vazias ("") e espaços (" ")
print("Valores vazios (''):", (casco['modelo'] == '').sum())
print("Valores com espaço (' '):", (casco['modelo'] == ' ').sum())

# E também aqueles que podem ter mais de um espaço
print("Valores apenas com espaços:", casco['modelo'].str.strip().eq('').sum())

Valores vazios (''): 0
Valores com espaço (' '): 0
Valores apenas com espaços: 0

In [46]:
# Mostrar algumas linhas onde o valor é nulo ou vazio
casco[casco['modelo'].isna() | casco['modelo'].str.strip().eq('')].head(10)

,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio,categoria_desc,regiao_cod,regiao_desc
564,NaN,2018,Jurídica,5,0.45,702.15,0,0,34000.00,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,35,AC - Acre
745,NaN,2013,F,5,0.50,548.44,0,0,31212.00,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,2,RS - Demais regiões
799,NaN,2015,F,2,0.50,445.58,0,0,40800.00,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,4,SC - Oeste
1287,NaN,2018,M,5,0.43,336.72,0,0,43900.00,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,1,RS - Met. Porto Alegre e Caxias do Sul
1509,NaN,2020,F,5,0.09,229.53,0,0,119414.44,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,11,SP - Met. de São Paulo
1530,NaN,2020,F,4,0.22,445.52,0,0,103496.19,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,2,RS - Demais regiões
2156,NaN,2016,F,5,0.50,639.93,0,0,46004.00,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,39,GO - Goiás
2291,NaN,2016,M,3,0.01,9.92,0,0,27573.00,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,17,MG - Vale do Aço-Norte-Vale Jequitinhonha
3775,NaN,2015,F,2,0.28,295.49,0,0,42020.00,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,13,SP - Ribeirão Preto e Demais Mun. de Campinas
3838,NaN,2020,F,3,0.69,1388.38,0,0,115373.51,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,7,PR - Met. Curitiba

In [47]:
# Substituição dos valores Nan por 'Não informado'
casco['modelo'] = casco['modelo'].replace(['', ' ', '  '], np.nan)
casco['modelo'] = casco['modelo'].fillna('Não informado')

In [53]:
casco.head()

,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio,categoria_desc,regiao_cod,regiao_desc
0,RENAULT DUSTER,2016,M,3,6.75,8112.76,0,0,59889.52,0,0,0,0,0,0,0,0,3,345,2019B,Carro_nacional,12,SP - Grande Campinas
1,RENAULT SANDERO,2015,Jurídica,3,1.08,1232.99,0,0,32457.32,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,12,SP - Grande Campinas
2,FIAT STRADA,2014,M,4,0.50,884.72,0,0,46034.00,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,12,SP - Grande Campinas
3,FIAT TORO,2019,Jurídica,5,5.03,15386.13,0,0,130695.64,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,7,PR - Met. Curitiba
4,LAND ROVER DISCOVERY,2012,Não definido,0,0.50,1291.73,0,0,134337.99,0,0,0,0,0,0,0,0,0,0,2019B,Utilitários,21,BA - Bahia

### FAIXA ETARIA

Para a variável 'FAIXA ETÁRIA':

Os códigos estão na tabela auxiliar 'auto_idade' que possui definição no Manual da Autoseg;

Definição: auto_idade – código e descrição de faixas etárias;

Como são poucos códigos, vamos criar o dicionário de forma manual;

Realizar a substituição.

Manual da Autoseg:

Categoria:
* 0: Não informada
* 1: Entre 18 e 25 anos  
* 2: Entre 26 e 35 anos
* 3: Entre 36 e 45 anos
* 4: Entre 46 e 55 anos
* 5: Maior que 55 anos

In [54]:
# Observação dos valores únicos da coluna faixa_etaria
casco['faixa_etaria'].unique()

array([3, 4, 5, 0, 2, 1])

In [55]:
casco['faixa_etaria'].value_counts()

faixa_etaria
5    667609
3    663066
4    614252
2    512952
0    499750
1    170977
Name: count, dtype: int64

In [56]:
# criação do dicionário de faixas_etárias
faixa_d = {
    0: 'Não informada',
    1: 'Entre 18 e 25 anos',
    2: 'Entre 26 e 35 anos',
    3: 'Entre 36 e 45 anos',
    4: 'Entre 46 e 55 anos',
    5: 'Maior que 55 anos',
}

# Criamos uma nova coluna com a descrição da categoria (categoria_desc)
# e colocamos a descrição do dicionário usando a função map
casco['faixa_desc'] = casco['faixa_etaria'].map(faixa_d).astype('string')

# (opcional) transformar em categórico para análises/plots mais leves
# casco['categoria_desc'] = casco['categoria_desc'].astype('category')

# checar
casco[['faixa_etaria','faixa_desc']].head()

   faixa_etaria          faixa_desc
0             3  Entre 36 e 45 anos
1             3  Entre 36 e 45 anos
2             4  Entre 46 e 55 anos
3             5   Maior que 55 anos
4             0       Não informada

In [57]:
casco.head(5)

,modelo,ano,sexo,faixa_etaria,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio,categoria_desc,regiao_cod,regiao_desc,faixa_desc
0,RENAULT DUSTER,2016,M,3,6.75,8112.76,0,0,59889.52,0,0,0,0,0,0,0,0,3,345,2019B,Carro_nacional,12,SP - Grande Campinas,Entre 36 e 45 anos
1,RENAULT SANDERO,2015,Jurídica,3,1.08,1232.99,0,0,32457.32,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,12,SP - Grande Campinas,Entre 36 e 45 anos
2,FIAT STRADA,2014,M,4,0.50,884.72,0,0,46034.00,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,12,SP - Grande Campinas,Entre 46 e 55 anos
3,FIAT TORO,2019,Jurídica,5,5.03,15386.13,0,0,130695.64,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,7,PR - Met. Curitiba,Maior que 55 anos
4,LAND ROVER DISCOVERY,2012,Não definido,0,0.50,1291.73,0,0,134337.99,0,0,0,0,0,0,0,0,0,0,2019B,Utilitários,21,BA - Bahia,Não informada

In [58]:
# Dropando as colunas 'faixa_etaria' do nosso DF.
casco.drop(['faixa_etaria'], axis=1, inplace=True)

In [59]:
casco.head()

,modelo,ano,sexo,exposicao1,premio1,exposicao2,premio2,is_media,freq_sin1,indeniz1,freq_sin2,indeniz2,freq_sin3,indeniz3,freq_sin4,indeniz4,freq_sin9,indeniz9,envio,categoria_desc,regiao_cod,regiao_desc,faixa_desc
0,RENAULT DUSTER,2016,M,6.75,8112.76,0,0,59889.52,0,0,0,0,0,0,0,0,3,345,2019B,Carro_nacional,12,SP - Grande Campinas,Entre 36 e 45 anos
1,RENAULT SANDERO,2015,Jurídica,1.08,1232.99,0,0,32457.32,0,0,0,0,0,0,0,0,0,0,2019B,Carro_nacional,12,SP - Grande Campinas,Entre 36 e 45 anos
2,FIAT STRADA,2014,M,0.50,884.72,0,0,46034.00,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,12,SP - Grande Campinas,Entre 46 e 55 anos
3,FIAT TORO,2019,Jurídica,5.03,15386.13,0,0,130695.64,0,0,0,0,0,0,0,0,0,0,2019B,Pick-up,7,PR - Met. Curitiba,Maior que 55 anos
4,LAND ROVER DISCOVERY,2012,Não definido,0.50,1291.73,0,0,134337.99,0,0,0,0,0,0,0,0,0,0,2019B,Utilitários,21,BA - Bahia,Não informada

Warning: Total number of columns (23) exceeds max_columns (20) limiting to first (20) columns.

In [60]:
casco.columns

Index(['modelo', 'ano', 'sexo', 'exposicao1', 'premio1', 'exposicao2',
       'premio2', 'is_media', 'freq_sin1', 'indeniz1', 'freq_sin2', 'indeniz2',
       'freq_sin3', 'indeniz3', 'freq_sin4', 'indeniz4', 'freq_sin9',
       'indeniz9', 'envio', 'categoria_desc', 'regiao_cod', 'regiao_desc',
       'faixa_desc'],
      dtype='object')

In [61]:
casco.dtypes

modelo                    object
ano                       object
sexo                      object
exposicao1               float64
premio1                  float64
exposicao2                 int64
premio2                    int64
is_media                 float64
freq_sin1                  int64
indeniz1                   int64
freq_sin2                  int64
indeniz2                   int64
freq_sin3                  int64
indeniz3                   int64
freq_sin4                  int64
indeniz4                   int64
freq_sin9                  int64
indeniz9                   int64
envio                     object
categoria_desc          category
regiao_cod                 Int64
regiao_desc               object
faixa_desc        string[python]
dtype: object

In [64]:
# Remover espaços em branco e substituir pontos por nada
casco['ano'] = casco['ano'].astype(str).str.strip().str.replace('.', '', regex=False)

In [65]:
# Substituir valores problemáticos por NaN
casco['ano'] = casco['ano'].replace(['', ' ', '0000', '.', '   .', '    '], np.nan)

# Converter para numérico (forçando erro → NaN)
casco['ano'] = pd.to_numeric(casco['ano'], errors='coerce')

In [66]:
# Converter para tipo inteiro compatível com NaN
casco['ano'] = casco['ano'].astype('Int64')

In [67]:
casco['ano'].dtypes
casco['ano'].unique()

<IntegerArray>
[2016, 2015, 2014, 2019, 2012, 2001, 2010, 2018, 1989, 2008, 2013, 2005, 2011,
 1993, 2017, 2006, 2098, 2020, 2009, 2007, 2097, 2002, 2004, 2000, 1996, 2003,
 1994,    0, 1998, 1997, 1999, 2095, 1981, 1983, 1991, 1985, 1995, 1986, 1992,
 1987, 1979, 1990, 1988, 1977, 1973, 1984, 2096, 2099, 1976, 2093, 1975, 1980,
 1978, 1961, 1966, 1982, 1974, 1972, 1970, 1969, 1962, 1950, 1965, 1971, 1952,
 2094, 1968, 2091, 1957, 1967, 1960, 2092, 1959, 1958, 1963, 1954, 1964, 1951,
 1922, 1953, 2090, <NA>,  201, 2087]
Length: 84, dtype: Int64

In [68]:
# Substituir o ano 0 por <NA>
casco.loc[casco['ano'] == 0, 'ano'] = pd.NA

In [69]:
# Corrigir anos com erros de digitação

# Corrigir o ano 201 -> 2001
casco.loc[casco['ano'] == 201, 'ano'] = 2001

# Corrigir anos acima de 2025 (ex: 2087, 2099, 2095...) subtraindo 100
casco.loc[casco['ano'] > 2025, 'ano'] = casco.loc[casco['ano'] > 2025, 'ano'] - 100

# Reconfirmar o tipo
casco['ano'] = casco['ano'].astype('Int64')

In [70]:
casco['ano'].unique()

<IntegerArray>
[2016, 2015, 2014, 2019, 2012, 2001, 2010, 2018, 1989, 2008, 2013, 2005, 2011,
 1993, 2017, 2006, 1998, 2020, 2009, 2007, 1997, 2002, 2004, 2000, 1996, 2003,
 1994, <NA>, 1999, 1995, 1981, 1983, 1991, 1985, 1986, 1992, 1987, 1979, 1990,
 1988, 1977, 1973, 1984, 1976, 1975, 1980, 1978, 1961, 1966, 1982, 1974, 1972,
 1970, 1969, 1962, 1950, 1965, 1971, 1952, 1968, 1957, 1967, 1960, 1959, 1958,
 1963, 1954, 1964, 1951, 1922, 1953]
Length: 71, dtype: Int64

In [71]:
casco.dtypes

modelo                    object
ano                        Int64
sexo                      object
exposicao1               float64
premio1                  float64
exposicao2                 int64
premio2                    int64
is_media                 float64
freq_sin1                  int64
indeniz1                   int64
freq_sin2                  int64
indeniz2                   int64
freq_sin3                  int64
indeniz3                   int64
freq_sin4                  int64
indeniz4                   int64
freq_sin9                  int64
indeniz9                   int64
envio                     object
categoria_desc          category
regiao_cod                 Int64
regiao_desc               object
faixa_desc        string[python]
dtype: object

## Exportação de Arquivo CSV **tratado**

In [72]:
casco.to_csv('casco_tratado.csv', index=False, encoding='utf-8-sig')